### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mat-sz** [mat-sz/metastable#1]
**Soon:**
- [ ] PixArt models support
- [ ] Better recommended model sections and a more clear message on first install.
- [ ] Ability to add other folders with models (instead of having to copy/symlink).
